export const events = {
  results: {
    dedlines: [
      {
        title: "AI 빅테이터 하반기 교육",
        category: "IT",
        date: "11월 26일(월) 전북",
        deadline: 8,
        poster_path: "images//deadline1.jpg",
      },
      {
        title: "Blockchain Conference",
        category: "IT",
        date: "11월 24일(금) 강남구",
        deadline: 6,
        poster_path: "images//deadline2.png",
      },
      {
        title: "2023 롯데벤처스 데모데이",
        category: "IT",
        date: "11월 20일(수) 온라인",
        deadline: 2,
        poster_path: "images//deadline3.png",
      },
      {
        title: "IR컨설턴트 14기 자격증 설명회",
        category: "자격증",
        date: "11월 21일(월)",
        deadline: 3,
        poster_path: "images//deadline4.png",
      },
      {
        title: "1인창업 세미나",
        category: "창업",
        date: "11월 22일(월)",
        deadline: 4,
        poster_path: "images//deadline5.jpg",
      },
      {
        title: "춘천벤처클럽",
        category: "창업",
        date: "11월 24일(월)",
        deadline: 6,
        poster_path: "images//deadline6.png",
      },
      //
      {
        title: "AI 빅테이터 하반기 교육",
        category: "IT",
        date: "11월 26일(월) 전북",
        deadline: 8,
        poster_path: "images//deadline1.jpg",
      },
      {
        title: "Blockchain Conference",
        category: "IT",
        date: "11월 24일(금) 강남구",
        deadline: 6,
        poster_path: "images//deadline2.png",
      },
      {
        title: "2023 롯데벤처스 데모데이",
        category: "IT",
        date: "11월 20일(수) 온라인",
        deadline: 2,
        poster_path: "images//deadline3.png",
      },
      {
        title: "IR컨설턴트 14기 자격증 설명회",
        category: "자격증",
        date: "11월 21일(월)",
        deadline: 3,
        poster_path: "images//deadline4.png",
      },
      {
        title: "1인창업 세미나",
        category: "창업",
        date: "11월 22일(월)",
        deadline: 4,
        poster_path: "images//deadline5.jpg",
      },
      {
        title: "춘천벤처클럽",
        category: "창업",
        date: "11월 24일(월)",
        deadline: 6,
        poster_path: "images//deadline6.png",
      },
    ],

    new: [
      {
        title: "여성벤처엑셀러레이팅 프로그램",
        category: "창업",
        date: "11월 29일(수) 온라인",
        deadline: 11,
        poster_path: "images//new1.jpg",
      },
      {
        title: "월간 북커뮤니티",
        category: "도서",
        date: "11월 28일(화) 성남시",
        deadline: 10,
        poster_path: "images//new2.png",
      },
      {
        title: "ONUS IP 찾아가는 오피스아워",
        category: "사무",
        date: "11월 28일(화) 종로구",
        deadline: 10,
        poster_path: "images//new3.jpg",
      },
      {
        title: "찾아가는 스타트업 커리어",
        category: "창업",
        date: "11월 20일(월)",
        deadline: 2,
        poster_path: "images//new4.jpg",
      },
      {
        title: "AWE 여성창업 아카데미",
        category: "창업",
        date: "11월 22일(수) 종로구",
        deadline: 4,
        poster_path: "images//new5.png",
      },
      {
        title: "비버스클럽",
        category: "IT",
        date: "11월 24일(월)",
        deadline: 6,
        poster_path: "images//new6.png",
      }, //
      ,
      {
        title: "여성벤처엑셀러레이팅 프로그램",
        category: "창업",
        date: "11월 29일(수) 온라인",
        deadline: 11,
        poster_path: "images//new1.jpg",
      },
      {
        title: "월간 북커뮤니티",
        category: "도서",
        date: "11월 28일(화) 성남시",
        deadline: 10,
        poster_path: "images//new2.png",
      },
      {
        title: "ONUS IP 찾아가는 오피스아워",
        category: "사무",
        date: "11월 28일(화) 종로구",
        deadline: 10,
        poster_path: "images//new3.jpg",
      },
      {
        title: "찾아가는 스타트업 커리어",
        category: "창업",
        date: "11월 20일(월)",
        deadline: 2,
        poster_path: "images//new4.jpg",
      },
      {
        title: "AWE 여성창업 아카데미",
        category: "창업",
        date: "11월 22일(수) 종로구",
        deadline: 4,
        poster_path: "images//new5.png",
      },
      {
        title: "비버스클럽",
        category: "IT",
        date: "11월 24일(월)",
        deadline: 6,
        poster_path: "images//new6.png",
      },
    ],

    now: [
      {
        title: "디지털마케팅연구회",
        category: "세미나",
        date: "11월 22일(수) 강남구",
        deadline: 4,
        poster_path: "images//now1.jpg",
      },
      {
        title: "생각과 같이 사는 방법",
        category: "도서",
        date: "11월 21일(화) 강남구",
        deadline: 3,
        poster_path: "images//now2.jpg",
      },
      {
        title: "2023 청년 스타트업 살롱",
        category: "사무",
        date: "11월 28일(화) 종로구",
        deadline: 10,
        poster_path: "images//now3.jpg",
      },
      {
        title: "신한 Future's Lab Demo Day",
        category: "연구",
        date: "11월 22일(수) 영등포구",
        deadline: 4,
        poster_path: "images//now4.png",
      },
      {
        title: "현직속기사 특별강연",
        category: "언론",
        date: "11월 23일(목) 온라인",
        deadline: 5,
        poster_path: "images//now5.jpg",
      },
      {
        title: "이노벤처 커넥트",
        category: "IT",
        date: "12월 12일(화) 강남구",
        deadline: 24,
        poster_path: "images//now6.png",
      },
 ,     //
 {
  title: "디지털마케팅연구회",
  category: "세미나",
  date: "11월 22일(수) 강남구",
  deadline: 4,
  poster_path: "images//now1.jpg",
},
{
  title: "생각과 같이 사는 방법",
  category: "도서",
  date: "11월 21일(화) 강남구",
  deadline: 3,
  poster_path: "images//now2.jpg",
},
{
  title: "2023 청년 스타트업 살롱",
  category: "사무",
  date: "11월 28일(화) 종로구",
  deadline: 10,
  poster_path: "images//now3.jpg",
},
{
  title: "신한 Future's Lab Demo Day",
  category: "연구",
  date: "11월 22일(수) 영등포구",
  deadline: 4,
  poster_path: "images//now4.png",
},
{
  title: "현직속기사 특별강연",
  category: "언론",
  date: "11월 23일(목) 온라인",
  deadline: 5,
  poster_path: "images//now5.jpg",
},
{
  title: "이노벤처 커넥트",
  category: "IT",
  date: "12월 12일(화) 강남구",
  deadline: 24,
  poster_path: "images//now6.png",
},
    ],
  },
};
